var annotated_dup =
[
    [ "cJSON", "structcJSON.html", "structcJSON" ],
    [ "cJSON_Hooks", "structcJSON__Hooks.html", "structcJSON__Hooks" ],
    [ "Oct_Allocator_t", "structOct__Allocator__t.html", "structOct__Allocator__t" ],
    [ "Oct_AssetBundle_t", "structOct__AssetBundle__t.html", "structOct__AssetBundle__t" ],
    [ "Oct_AssetData_t", "structOct__AssetData__t.html", "structOct__AssetData__t" ],
    [ "Oct_AssetLink_t", "structOct__AssetLink__t.html", "structOct__AssetLink__t" ],
    [ "Oct_AudioCommand_t", "structOct__AudioCommand__t.html", "structOct__AudioCommand__t" ],
    [ "Oct_AudioData_t", "structOct__AudioData__t.html", "structOct__AudioData__t" ],
    [ "Oct_BitmapFontData_t", "structOct__BitmapFontData__t.html", "structOct__BitmapFontData__t" ],
    [ "Oct_CameraUpdate_t", "structOct__CameraUpdate__t.html", "structOct__CameraUpdate__t" ],
    [ "Oct_Circle_t", "structOct__Circle__t.html", "structOct__Circle__t" ],
    [ "Oct_Colour_t", "structOct__Colour__t.html", "structOct__Colour__t" ],
    [ "Oct_Command_t", "structOct__Command__t.html", "structOct__Command__t" ],
    [ "Oct_Context_t", "structOct__Context__t.html", "structOct__Context__t" ],
    [ "Oct_DrawCommand_t", "structOct__DrawCommand__t.html", "structOct__DrawCommand__t" ],
    [ "Oct_FileHandle_t", "structOct__FileHandle__t.html", "structOct__FileHandle__t" ],
    [ "Oct_FontAtlasData_t", "structOct__FontAtlasData__t.html", "structOct__FontAtlasData__t" ],
    [ "Oct_FontData_t", "structOct__FontData__t.html", "structOct__FontData__t" ],
    [ "Oct_FontGlyphData_t", "structOct__FontGlyphData__t.html", "structOct__FontGlyphData__t" ],
    [ "Oct_InitInfo_t", "structOct__InitInfo__t.html", "structOct__InitInfo__t" ],
    [ "Oct_LoadCommand_t", "structOct__LoadCommand__t.html", "structOct__LoadCommand__t" ],
    [ "Oct_MetaCommand_t", "structOct__MetaCommand__t.html", "structOct__MetaCommand__t" ],
    [ "Oct_Rectangle_t", "structOct__Rectangle__t.html", "structOct__Rectangle__t" ],
    [ "Oct_ShaderData_t", "structOct__ShaderData__t.html", "structOct__ShaderData__t" ],
    [ "Oct_SpriteData_t", "structOct__SpriteData__t.html", "structOct__SpriteData__t" ],
    [ "Oct_SpriteFrame_t", "structOct__SpriteFrame__t.html", "structOct__SpriteFrame__t" ],
    [ "Oct_SpriteInstance_t", "structOct__SpriteInstance__t.html", "structOct__SpriteInstance__t" ],
    [ "Oct_TextureData_t", "structOct__TextureData__t.html", "structOct__TextureData__t" ],
    [ "Oct_Tilemap_t", "structOct__Tilemap__t.html", "structOct__Tilemap__t" ],
    [ "Oct_WindowCommand_t", "structOct__WindowCommand__t.html", "structOct__WindowCommand__t" ],
    [ "Oct_WindowEvent_t", "structOct__WindowEvent__t.html", "structOct__WindowEvent__t" ]
];